keys:
  # Users
  - &users: # nix-shell -p age --run 'age-keygen'
    - &badele age15js628ku59g94njn0vup20r4xx34guesgsj5dqsken5hma2zqg2szjed66
  # Hosts
  - &hosts: # nix-shell -p ssh-to-age --run 'cat hosts/<hostname>/ssh_host_ed25519_key.pub | ssh-to-age'
    - &latino age12lhx7ktnd4fvqjeq06h0z25n0s0a3r0ap6thzsxwuxvglqsjufls8mhk9u

creation_rules:
  - path_regex: secrets.ya?ml$
    key_groups:
      - age:
          - *badele
          - *latino